# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
  branches:
    include:
    - master
    
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.2 < 2.6'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    bundle update jekyll
    bundle install
    jekyll build
  displayName: 'jekyll build'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonarcloud'
    organization: 'ustdigital'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: sonar-sgds-demo1
    cliProjectName: sgds-demo-1
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'Sonarcloud'
    organization: 'ustdigital'
- task: CopyFiles@2
  displayName: 'Copy _site to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: _site
    TargetFolder: $(Build.ArtifactStagingDirectory)
- task: CopyFiles@2
  displayName: 'Copy test script to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: test
    TargetFolder: $(Build.ArtifactStagingDirectory)    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    ArtifactName: drop
